# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: H0M3
subtitle: by KAMSC
email: kamsc.h0m3@icloud.com
description: A responsive general purpose site <br /> by KAMSC Students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kamsc.github.io/" # the base hostname & protocol for your site
blog_url: "https://kamsc.github.io/blog/"
author: KAMSC Students
street_address: 600 West Vine Street Suite 400
city: Kalamazoo
state: MI
zip_code: 49008
country: United States of America
phone: (269) 337-0004

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: KAMSC
twitter_username: _KAMSC_
google_username: KAMSC
instagram_username:
facebook_username: KAMSC
dribble_username:

github_url: https://github.com/KAMSC
twitter_url: https://twitter.com/_KAMSC_
facebook_url: https://www.facebook.com/pages/Kalamazoo-Area-Mathematics-and-Science-Center/107893655910450
instagram_url:
dribble_url:
google_url: https://plus.google.com/117398504371614326665

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
