# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: H0M3
subtitle: by KAMSC
email: kamsc.h0m3@icloud.com
description: A responsive general purpose site <br /> by KAMSC Students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kamsc.github.io/" # the base hostname & protocol for your site
author: KAMSC Students
street_address: 600 West Vine Street Suite 400
city: Kalamazoo
state: MI
zip_code: 49008
country: United States of America
phone: (269) 337-0004

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: KAMSC
twitter_username: _KAMSC_
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
